app = 'eatsmart'
primary_region = 'cdg'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

# 🚀 AJOUTE CE BLOC POUR CRÉER UN "WORKER" PERMANENT :
[processes]
  app = "node src/index.js" # Assure-toi que c'est bien le chemin vers ton fichier principal (ex: src/index.js)

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512